CREATE TABLE IF NOT EXISTS import_sessions (
  id TEXT PRIMARY KEY NOT NULL,
  filename TEXT NOT NULL,
  status TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
