import type { AgentMessage } from "./types";

/** Representative payloads for every supported Agent message type (gallery). */
export interface AgentMessagePreviewItem {
  id: string;
  label: string;
  caption: string;
  message: AgentMessage;
}

export const AGENT_MESSAGE_PREVIEWS: AgentMessagePreviewItem[] = [
  { id: "markdown", label: "Text / Markdown", caption: "Narrative answers with headings, emphasis, lists and inline code.", message: { role: "agent", type: "markdown", content: "## Requirement analysis\nThe login flow has **three high-risk paths**:\n- Invalid password retry and lockout\n- Session expiry after 30 minutes\n- Role-based redirect to `dashboard`" } },
  { id: "hitl", label: "HITL approval", caption: "Approve or reject a proposal and send a human comment back to the agent.", message: { role: "agent", type: "hitl", data: { title: "Add 12 generated cases to the regression suite?", description: "This will create draft cases and link them to requirement AUTH-142. Existing cases will not be changed.", risk: "Medium impact" } } },
  { id: "actions", label: "AI actions", caption: "Actionable suggestions can be applied independently without hiding the rationale.", message: { role: "agent", type: "actions", data: { title: "Coverage improvements", detail: "I found two gaps after comparing the draft with the requirement.", actions: [{ label: "Add lockout recovery", description: "Covers cooldown expiry and a successful retry.", cta: "Add case" }, { label: "Strengthen session assertion", description: "Verify the refresh token is invalidated server-side.", cta: "Update" }] } } },
  { id: "table", label: "Editable table", caption: "Edit cells and headers, add rows or columns, or paste a range directly from Excel.", message: { role: "agent", type: "table", data: { title: "Coverage matrix", columns: [{ key: "area", label: "Area" }, { key: "coverage", label: "Coverage" }, { key: "risk", label: "Risk" }], rows: [{ area: "Happy path", coverage: "3 cases", risk: "Covered" }, { area: "Account lockout", coverage: "1 case", risk: "Needs edge case" }, { area: "Session expiry", coverage: "2 cases", risk: "Covered" }] } } },
  { id: "qa", label: "Agent questions", caption: "The Agent asks for missing context and the user writes and submits each answer.", message: { role: "agent", type: "qa", data: { title: "I need two details before generating cases", items: [{ id: "lockout", question: "After how many failed attempts should the account be locked?", context: "This determines the boundary cases and retry coverage.", placeholder: "For example: 5 attempts within 15 minutes" }, { id: "unlock", question: "How can a locked account be unlocked?", context: "Choose the supported recovery path or describe another one.", placeholder: "For example: automatically after 30 minutes" }] } } },
  { id: "mindmap", label: "Mind map", caption: "A concise fishbone view for complex scope, risks and test dimensions.", message: { role: "agent", type: "mindmap", data: { title: "Checkout quality model", center: "Reliable checkout", branches: [{ label: "Cart rules", items: ["Inventory reservation", "Quantity limits", "Price refresh", "Bundle removal"] }, { label: "Customer", items: ["Guest checkout", "Signed-in profile", "B2B account", "Restricted region"] }, { label: "Payment", items: ["3DS challenge", "Wallet fallback", "Partial failure", "Duplicate callback"] }, { label: "Fulfilment", items: ["Split shipment", "Store pickup", "Address validation", "Delivery window"] }, { label: "Promotion", items: ["Stacking rules", "Expired coupon", "Loyalty credit", "Currency rounding"] }, { label: "Recovery", items: ["Idempotent retry", "Session restore", "Inventory release", "Audit trail"] }] } } },
  { id: "swimlane", label: "Swimlane", caption: "Responsibilities and hand-offs across users, UI and services.", message: { role: "agent", type: "swimlane", data: { title: "Account lockout journey", lanes: [{ name: "User", steps: ["Submit password", "Retry", "Wait / recover"] }, { name: "Web app", steps: ["Validate input", "Show attempts", "Show lockout"] }, { name: "Auth API", steps: ["Reject login", "Increment count", "Lock account"] }] } } },
  { id: "flowchart", label: "Flowchart", caption: "A compact staged view for complex decisions, parallel paths and merged outcomes.", message: { role: "agent", type: "flowchart", data: { title: "Adaptive sign-in flow", nodes: [{ id: "start", label: "Submit identity and credentials", kind: "start", stage: 0 }, { id: "policy", label: "Sign-in method allowed?", kind: "decision", stage: 1 }, { id: "credentials", label: "Credentials valid?", kind: "decision", stage: 2 }, { id: "deny-policy", label: "Block unsupported method", kind: "end", stage: 2 }, { id: "risk", label: "Evaluate device and location risk", kind: "decision", stage: 3 }, { id: "attempts", label: "Update failed-attempt counter", kind: "step", stage: 3 }, { id: "session", label: "Create session and rotate token", kind: "step", stage: 4 }, { id: "mfa", label: "Complete MFA challenge", kind: "decision", stage: 4 }, { id: "lock", label: "Lock or allow another retry", kind: "decision", stage: 4 }, { id: "audit", label: "Write security audit event", kind: "step", stage: 5 }, { id: "deny", label: "Return safe failure response", kind: "end", stage: 5 }, { id: "success", label: "Continue to requested product", kind: "end", stage: 6 }], edges: [{ from: "start", to: "policy" }, { from: "policy", to: "credentials", label: "Allowed" }, { from: "policy", to: "deny-policy", label: "Blocked" }, { from: "credentials", to: "risk", label: "Valid" }, { from: "credentials", to: "attempts", label: "Invalid" }, { from: "risk", to: "session", label: "Low risk" }, { from: "risk", to: "mfa", label: "Elevated" }, { from: "attempts", to: "lock" }, { from: "mfa", to: "session", label: "Verified" }, { from: "mfa", to: "deny", label: "Failed" }, { from: "lock", to: "deny", label: "Locked" }, { from: "lock", to: "credentials", label: "Retry" }, { from: "session", to: "audit" }, { from: "audit", to: "success" }] } } },
];
